### ISSUE TITLE
Create Avatar for the Current User

### ISSUE THREAD

**Issue by ramonpbarros** [ummjhall/Routini#12]
Creates and returns the user's Avatar.

- [x] An authenticated user is required for a successful response
- [x] New avatar exists in the database after request
- [x] Avatar data returned includes `id`, `user_id`, `name`, `bio`, `level`, `health`, `exp`, `gold`, `gems`, `equip_head_id`, `equip_main_id`, `equip_armor_id`, `image_url`, `created_at`, and `updated_at`
- [x] Error response with status 400 is given when body validations for `name` are violated
- [x] Error response with status 400 is given when the user already has an avatar

**Comment by ummjhall** [comment]
400 Bad Request response include
"errors": {"name": "Name is required"}

**Comment by ramonpbarros** [comment]
Issue resolved.

**Comment by ummjhall** [comment]
Body validation error response should still have "Name is required" when the request is empty. Currently if the request is empty, it's just a message of "Bad Request".

If the user already has an avatar, it gives a body validation error response with "Name is required", but it should be a separate error. I added this check to the card and the api doc.
