### ISSUE TITLE
Edit the Current User's Avatar

### ISSUE THREAD

**Issue by ramonpbarros** [ummjhall/Routini#14]
Edits the Avatar's name/bio;
Updates level, health, exp, gold, and gems;
Equips or unequips a piece of Equipment

- [x] An authenticated user is required for a successful response
- [x] Avatar record is updated in the database after request
- [x] Avatar data returned includes `id`, `user_id`, `name`, `bio`, `level`, `health`, `exp`, `gold`, `gems`, `equip_head_id`, `equip_main_id`, `equip_armor_id`, `image_url`, `created_at`, and `updated_at`
- [x] Error response with status 404 is given when the user does not currently have an avatar

**Comment by ummjhall** [comment]
Let's get rid of the body validation error

**Comment by ummjhall** [comment]
Success response doesn't include image_url

Error response when the user doesn't have an avatar is 'Reward not found'

**Comment by ramonpbarros** [comment]
Issue resolved.
