### ISSUE TITLE
Create a Reward for the Current User

### ISSUE THREAD

**Issue by ramonpbarros** [ummjhall/Routini#16]
Creates and returns a new Reward for the user.

- [x] An authenticated user is required for a successful response
- [x] New reward exists in the database after request
- [x] Reward data returned includes `id`, `user_id`, `type`, `title`, `description`, `cost`, `created_at`, and `updated_at`
- [x] Error response with status 400 is given when body validations for `type`, `title`, or `cost` are violated

**Comment by ummjhall** [comment]
When sending data without the required fields, the app crashes instead of sending a body validation error response.

**Comment by ramonpbarros** [comment]
Issue Resolved and merged to the dev branch.

**Comment by ummjhall** [comment]
Body validation errors: 'Description' is not required.
Also we should capitalize "Cost" for consistency.

**Comment by ramonpbarros** [comment]
Reviewed issue and hopefully ready for release.
