### ISSUE TITLE
Delete a Reward belonging to the Current User

### ISSUE THREAD

**Issue by ramonpbarros** [ummjhall/Routini#18]
Deletes a user's existing Reward.

- [x] An authenticated user is required for a successful response
- [x] Only the owner of the reward is authorized to delete
- [x] Reward record is removed from the database after request
- [x] Success response includes a `message` indicating a successful deletion
- [x] Error response with status 404 is given when a reward does not exist with the provided `id`

**Comment by ummjhall** [comment]
DANGER: Users can delete other users' rewards!!!

Also, let's change the url to add 'current': /api/rewards/current/<reward_id>

**Comment by ramonpbarros** [comment]
Issue Resolved.
