### ISSUE TITLE
Buy or collect a piece of Equipment for the Current User

### ISSUE THREAD

**Issue by ramonpbarros** [ummjhall/Routini#19]
Adds a piece of Equipment to the user's inventory and returns it.

- [x] An authenticated user is required for a successful response
- [x] New data exists in the database after request
- [x] Equipment data returned includes `id`, `avatar_id`, `equipment_id`, and `equipment_nickname`
- [x] Error response with status 400 is given when specified equipment is already owned by the user
- [x] Error response with status 404 is given when equipment does not exist with the provided `id`
- [x] Error response with status 404 is given when the user does not currently have an avatar

**Comment by ramonpbarros** [comment]
Reviewed issue and ready for release.

**Comment by ramonpbarros** [comment]
Even tho the current user has an empty array response from the GET method at /api/equipment/current, they still cannot purchase a new piece of equipment. When trying to use the POST method with equipment_id 1, we receive a 400 error with the message: "Equipment already owned."

**Comment by ummjhall** [comment]
Changed 'and' to a comma in query

**Comment by ramonpbarros** [comment]
Reviewed issue and ready for release.
