### ISSUE TITLE
Rename a piece of Equipment belonging to the Current User

### ISSUE THREAD

**Issue by ramonpbarros** [ummjhall/Routini#20]
Renames the user's piece of Equipment specified by id and returns it.

- [x] An authenticated user is required for a successful response
- [x] Equipment record is updated in the database after request
- [x] Equipment data returned includes `id`, `avatar_id`, `equipment_id`, `equipment_nickname`, `created_at`, and `updated_at`
- [x] Error response with status 400 is given when the user does not own the specified equipment
- [x] Error response with status 404 is given when equipment does not exist with the provided `id`
- [x] Error response with status 404 is given when the user does not currently have an avatar

**Comment by ramonpbarros** [comment]
While trying to change the nickname of some equipment, I got this error message: 

'exc.MultipleResultsFound(sqlalchemy.exc.MultipleResultsFound: **Multiple rows were found when exactly one was required**)' 

It showed a 500 Internal Server Error. Can you check it out and make sure we're sending back the right response?

**Comment by ummjhall** [comment]
Let's get rid of the body validation error

**Comment by ummjhall** [comment]
> While trying to change the nickname of some equipment, I got this error message:
> 
> 'exc.MultipleResultsFound(sqlalchemy.exc.MultipleResultsFound: **Multiple rows were found when exactly one was required**)'
> 
> It showed a 500 Internal Server Error. Can you check it out and make sure we're sending back the right response?

It's because I was only checking for equipment_id and not also avatar_id in the avatars_equipment table

**Comment by ramonpbarros** [comment]
WARNING: Users have the ability to rename equipment belonging to other users. Additionally, users can access equipment owned by others simply by sending an empty request body.

**Comment by ummjhall** [comment]
Changed 'and' to a comma in query
