### ISSUE TITLE
Remove a piece of Equipment from the Current User's inventory

### ISSUE THREAD

**Issue by ramonpbarros** [ummjhall/Routini#21]
Deletes a piece of owned Equipment from the user's inventory.

- [x] An authenticated user is required for a successful response
- [x] Equipment record is removed from the database after request
- [x] Success response includes a `message` indicating a successful deletion
- [x] Error response with status 400 is given when the user does not own the specified equipment
- [x] Error response with status 404 is given when equipment does not exist with the provided `id`
- [x] Error response with status 404 is given when the user does not currently have an avatar

**Comment by ramonpbarros** [comment]
I'm encountering the same issue when updating equipment. I think the problem might be with using `one_or_none()`. Maybe we should try using `query.get(<id>)` instead.

**Comment by ummjhall** [comment]
It's because I was only checking for equipment_id and not also avatar_id in the avatars_equipment table

**Comment by ramonpbarros** [comment]
WARNING: Users have the ability to delete equipment belonging to other users.

**Comment by ummjhall** [comment]
Changed 'and' to a comma in query

**Comment by ramonpbarros** [comment]
Issue reviewed and ready for release.
