### ISSUE TITLE
Sign Up a User

### ISSUE THREAD

**Issue by ramonpbarros** [ummjhall/Routini#5]
Creates a new user, logs them in as the current user, and returns the user's information.

- [x] New user exists in the database after request
- [x] Successful response includes newly-created `id`, `email` and `username`
- [x] Error response with status 500 is given when the specified email or username already exists
- [x] Error response with status 400 is given when body validations for `email` or `username` are violated

**Comment by ummjhall** [comment]
First name and last name will show up as null when creating a user. This is intentional.
Those fields were not already in the form, and I don't think the app needs it (it's not in Habitica either).
So I think we should delete those columns from the user model.

**Comment by ramonpbarros** [comment]
Reviewed issue and ready for release.
