### ISSUE TITLE
Get all of the Current User's Rewards

### ISSUE THREAD

**Issue by ummjhall** [ummjhall/Routini#50]
Returns all Rewards created by the user.

- [x] An authenticated user is required for a successful response
- [x] Seed data exists in the database for rewards to be returned
- [x] Successful response includes each reward created by the user
- [x] Reward data returned includes `id`, `user_id`, `type`, `title`, `description`, `cost`, `created_at`, and `updated_at`

**Comment by Amrani-Farouk-Hossam-Eddine** [comment]
Hi, i'm intersted in this issues if there is no one working on it currently

**Comment by ummjhall** [comment]
Hi Farouk, this actually a private group project for a software engineering class. The repo is only set to 'public' for evaluation. Thanks anyway for your interest.

**Comment by ramonpbarros** [comment]
Currently awaiting review on whether to retain the 'created_at' and 'updated_at' fields or to remove them.
