### ISSUE TITLE
Get all of the Current User's Equipment

### ISSUE THREAD

**Issue by ummjhall** [ummjhall/Routini#51]
Returns all of the user's owned Equipment.

- [x] An authenticated user is required for a successful response
- [x] Seed data exists in the database for equipment to be returned
- [x] Successful response includes each piece of equipment owned by the user
- [x] Equipment data returned includes `id`, `user_id`, `type`, `name`, `nickname`, `description`, `cost`, `image_url`, `created_at`, and `updated_at`
- [x] Error response with status 404 is given when the user does not currently have an avatar

**Comment by ramonpbarros** [comment]
Reviewed issue and ready for release.

**Comment by ramonpbarros** [comment]
Reviewed issue and ready for release.

**Comment by ramonpbarros** [comment]
The user is currently unable to retrieve their current equipment. They are encountering an error message indicating that multiple rows were found when only one was expected.

``` 
File "/Users/ramonbarros/Desktop/app-academy/projects/routini/Routini/.venv/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 614, in _only_one_row
    raise exc.MultipleResultsFound(
sqlalchemy.exc.MultipleResultsFound: Multiple rows were found when exactly one was required
```

**Comment by ramonpbarros** [comment]
Reviewed issue and ready for release.
