### ISSUE TITLE
Get all Tasks of the Current User

### ISSUE THREAD

**Issue by ramonpbarros** [ummjhall/Routini#6]
Returns all the Tasks created by the user.

- [x] An authenticated user is required for a successful response
- [x] Seed data exists in the database for tasks to be returned
- [x] Successful response includes each task created by the user
- [x] Task data returned includes `id`, `user_id`, `type`, `title`, `description`, `difficulty`, `start_date`, `repeats_every`, `due_date`, `created_at`, and `updated_at`

**Comment by nmilinovich** [comment]
finished besides created at and updated at

**Comment by ramonpbarros** [comment]
Reviewed issue and ready for release.
